opentargets/evidence_datasource_parsers

- common/HGNCParser.py
Improve current implementation, where it is possible that the mapping of a current gene symbol to Ensembl id is replaced by a previous symbol. For example, `TCF4` is both the symbol of `ENSG00000196628` and a synonym of `TCF7L2 - ENSG00000148737` and the current implementation maps `TCF4` to `ENSG00000148737`. This PR adds a test so that mappings of previous symbols are only stored if they don't already exist.
> Avoid previous symbols replacing mapping of current symbols

- modules/GeneticsPortal.py
This modification adds an extra option to the evidence generator script to specify a lower threshold of l2g score.
eg.:
```bash
python ${repo_directory}/modules/GeneticsPortal.py \
--inputFile ${dataFolder}/l2g_joined_exploded.2020.03.04.parquet \
--schemaFile https://raw.githubusercontent.com/opentargets/json_schema/Draft-4_compatible/opentargets.json \
--cores 3 \
--sample 1000 \
--outputFile output.json.gz \
--threshold 0.1
```
> Add optional l2g score filter.

- modules/GenomicsEnglandPanelApp.py
As discussed on Friday 13th, four changes have been made to the current Panel App parser:
1. `evidence.allelic_requirement` has been added;
2. `panel_id, panel_name, panel_version` have been changed to `study_id, study_name, study_version`. In addition, these fields are not only in `unique_association_fields` but also can be found under `evidence`;
3. `disease.source_name` now shows the phenotype of the evidence, not the original string;
4. `evidence.phenotypes_array` has been added, as an array listing all the phenotypes present in the source string
[This is an example](https://github.com/opentargets/evidence_datasource_parsers/files/5546478/test-results.json.gz) of a newly generated string.
Thinking about possible incompatibilities with FE, please see if we should limit the …
> [il-GEL] Updated script

- modules/Gene2Phenotype.py
Map G2P mutation consequence to SO as follows:
| Mutation Consequence | SO code | SO label |
| --- | --- | --- |
| loss of function | [SO_0002054](https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0002054) | loss_of_function_variant |
| all missense/in frame | [SO_0001650](https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0001650&viewMode=All&siblings=false) | inframe_variant |
| uncertain | [SO_0002220](https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0002220) | function_uncertain_variant |
| activating | [SO_0002053](https://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0002053) | gain_of_function_variant |
| …
> [G2P] Map mutation consequence to functional consequence and replace empty allelic requirement

- README.md
- modules/MouseModels.py
- settings.py
Two changes related to PhenoDigm:
- The output filename was lacking the gz extension
- Note added to the README to explain that the last (`-w`) may fail if the main step and the upload are run on different days because the date is automatically added to the file name.
> Ag phenodigm file extension

- README.md
- modules/Gene2Phenotype.py
- settings.py
Revamp of the Gene2Phenotype parser to align evidence strings with new schema. This is the summary of the changes made:
- JSON schema is NOT loaded
- Gene symbols are NOT mapped to Ensembl
- Evidence strings are stored as dictionaries and serialised as JSON
- Unique association fields have been removed because they are now controlled by the ETL pipeline.
- The script metadata has been removed from the code
- The scoring based on the classification/confidence has been removed.
- The mutation consequence is stored in `variantFunctionalConsequenceId`
Closes opentargets/platform#1279
> Ag g2p new schema 1279

- modules/PROGENY.py
- modules/SLAPEnrich.py
Changes to the SLAPEnrich and PROGENy parsers after the implementation of the pathways field into the schema described in [#1387](https://github.com/opentargets/platform/issues/1387).
> [pathways fix] 

- modules/GeneticsPortal.py
Adding beta to genetics portal evidence. This is the generated evidence when odds ratio and beta is given. Tried and script runs successfully. 
**beta is given:**
```json
{
"datasourceId": "ot_genetics_portal",
"datatypeId": "genetic_association",
"targetFromSourceId": "ENSG00000067606",
"diseaseFromSourceMappedId": "EFO_0004314",
"publicationFirstAuthor": "UKB Neale v2",
"publicationYear": 2018,
"diseaseFromSource": "Forced expiratory volume in 1-second (fev1), predicted",
"studyId": "NEALE2_20153_raw",
"studySampleSize": 117241,
"pValueMantissa": 5.802630000000002,
"pValueExponent": -9,
"beta": 0.00535037,
"betaConfidenceIntervalLower": 0.0035493887200000007,
"betaConfidenceIntervalUpper": 0.00715135128,
"resourceScore": 0.1838376522064209,
"variantRsId": "rs1692585",
"variantId": …
```
> Adding beta to parser

- resources/cancer2EFO_mappings.tsv
The more specific mapping Orphanet_573163 is not included in EFO at the moment, hence leading to invalid evidence strings.
We are going back to the less specific mapping "Paraganglioma" until we know whether it is possible to bring Orphanet_573163 into EFO.
> Update Orphanet_573163 to EFO_1000453

- modules/EPMC.py
In this branch there are two updates:
* From the epmc cooccurrence file we capture `pmcid` and is stored in the new field `pmcIds`. Which is a list.
* Now literature evidence is not discarded if pmid is not given if pmcid is present.
* `targetFromSource` and `diseaseFromSource` got removed from the evidence.
Example of the generated evidence where pmid is not given:
```json
{
"datasourceId": "europepmc",
"datatypeId": "literature",
"targetFromSourceId": "ENSG00000226344",
"diseaseFromSourceMappedId": "EFO_0000544",
"resourceScore": 10,
"literature": [],
"textMiningSentences": [
{
"text": "In contrast to the observation with PLP, the amount of E2 recovered from the CHAPS-insoluble membrane fraction did not increase 20 h after infection, as compared with 5 h (Fig. 3 c).",
"tStart": 55, …
```
> EPMC parser update

- modules/PhenoDigm.py
Fixing that annoying bug where Spark would coerce everything into float for internal comparisons, but still output the score as string and break the ETL pipeline
(Resubmitted with the proper branch name)
> Bug fix: Cast resourceScore as float

- Snakefile
- modules/PhenoDigm.py
Another round of updates from https://github.com/opentargets/platform/issues/1471.
Despite `mousePhenotypes` generation being of higher priority, it wasn't possible to fully implement before these changes are done.
* Separate MGI and Ensembl target identifiers in model
* Ingest, parse, process and join PubMed references
* Added stubs for `mousePhenotypes` generation and upload
> PhenoDigm evidence generation updates

- resources/cancer2EFO_mappings.tsv
The typo I mentioned in https://github.com/opentargets/evidence_datasource_parsers/commit/33ce8fe2ee30ab8070ffadce84b8c943f6579586 was not such.
intOGen and SLAPenrich both represent the seme disease (Diffuse large B-cell lymphoma / EFO_0000403) with two different acronyms: `DLBCL` and `DLBC` respectively.
When I changed the mapping file from DLBCL to DLBC to solve the unmapped intogen label, I introduced the bug where the SLAPenrich one wouldn't be matched.
I've just added another row to account for both representations.
> Update disease mapping for SLAPEnrich

- modules/GeneticsPortal.py
The current version of the parser lacks the logic to infer the source of an OT Genetics study.
I'm adding that by processing the authors of the studies.
> Add projectId to OTG

- modules/Gene2Phenotype.py
The release of Gene2Phenotypes dataset is out. There are a few changes that needed to address:
* Columns got renamed, new columns got introduced. 
* Variant consequences got changes. As the script maps consequence terms to SO codes, the mapping function had to be updated.
The script at this point runs just fine, validates no problem against the most recent schema. Example of the output:
```json
{
"diseaseFromSource": "Childhood-Onset, Slowly Progressive Nemaline Myopathy",
"datasourceId": "gene2phenotype",
"datatypeId": "genetic_literature",
"targetFromSourceId": "MYPN",
"confidence": "both RD and IF",
"studyId": "DD",
"literature": [
"28017374"
],
"allelicRequirements": [
"biallelic_autosomal"
],
"variantFunctionalConsequenceId": "SO_0002317"
}
```
> Update gene2phenotype parser for new field names.

- modules/TEP.py
Thank to the communication initiated by @andrewhercules , the [Structural Genomics Consortium](https://www.thesgc.org/) made the Target Enabling Packages (TEPs) available through a downloadable tsv file. This allowed us the following changes:
* Instead of parsing fragile html files, we can directly read data from a properly formatted table.
* We could increase consistency across other datasource parsers by using PySpark in favour of Pandas. 
* Shared modules used imported from `common.evidence`
The stable url for the data is hardcoded into the script. I think adding to the configuration does not make sense at this point.
> Updating the TEP parser

- Snakefile
- configuration.yaml
- modules/Gene2Phenotype.py
This PR covers the following updates around G2P datasource:
> Gene2Phenotype updates

- Snakefile
- common/ontology.py
- configuration.yaml
- modules/Gene2Phenotype.py
This PR captures the effort to make EFO version optional in the evidence generation pipeline. 
* The EFO release is fixed in the config file for each release.
* This version will be read by snakemake
* An env variable is created by snakemake
* Env variable is read by the efo fucntion in commons to initialise Ontoma object
Also Gene2Phenotype update: 
- Fetching `diseaseFromSourceId` from `disease mim` column and `disease ontology` columns. 
- Parsing dyadic disease labels to improve disease mapping.
> Making EFO optional for evidence parsers

- resources/pathway2Reactome_mappings.tsv
This PR updates the pending mappings between the perturbed pathways and their Reactome IDs that are exposed in the PROGENy evidence as described in [#713](https://github.com/opentargets/issues/issues/713)
Evidence looks fine and passes validation.
> Updated pathways to Reactome mappings

- modules/EPMC.py
Each EPMC evidence describes the t/d relationship in a given publication. We want to make the users able to filter the evidence by the publication year.
This PR processes the `year` field available in the cooccurrences to expose that in `publicationYear`. 
There are cases where more than one date is reported for the same publication. In this case we take the earlier year as the publication date (I checked some examples and this was accurate).
> Add year of publication to the EPMC evidence

- requirements-frozen.txt
- requirements.txt
Dependabot found a problematic pyspark version and recommended to change pyspark version to `3.1.3`. I didn't merge [dependabot's  PR](https://github.com/opentargets/evidence_datasource_parsers/pull/135), instead updated the requirements and requirements-frozen properly. 
Before merging, we have to make sure no pyspark functionality is broken. (the full pipeline needs to be re-run anyways.)
> Updating pyspark version.

- modules/IMPC.py
Closes https://github.com/opentargets/issues/issues/1805.
The following fields are now used to enforce uniqueness:
```python
'diseaseFromSource',  # Original disease name.
'targetInModel',  # Mouse gene name.
'biologicalModelAllelicComposition',  # Mouse model property.
'biologicalModelGeneticBackground',  # Mouse model property.
'diseaseFromSourceMappedId',  # EFO mapped disease ID.
'targetFromSourceId',  # Ensembl mapped human gene ID.
```
Evidence count decrease is now adequate, in its expected order of magnitude, to our expectations.
> Remove duplicated evidence from IMPC

- configuration.yaml
**Practically updating a few things:**
No other updates were made. This time the dependency issues were not addressed. Scoped under [#2834](https://github.com/opentargets/issues/issues/2834)
> feat: updating config for the 23.02 release

- partner_preview_scripts/ot_crispr.py
This is a parser for multiple OT funded CRISPR experiments actual as of Feb 14 2022.
**Script Input**:
* Data folder containing the files. You can download the files from [here](https://drive.google.com/drive/folders/1i__zI-oOZDn8zfUfvvgaN9hmb95AWUVB)
* Study table: a csv exported google sheet, containing general and experiment specific metadata eg. modelled disease, experiment specific confidence cutoff, original project id and description etc. This is it: `"https://docs.google.com/spreadsheets/d/1eow_rTizGY_Vda0Q-8sFNWCOyFkKRSUen1Em1ysPSiA/export?format=csv"`
**Other files used by the script defined by the parameter file**: These are required as data files for each study defined in the study table.
* `datafile`: data file in god knows what format.
* `controlDataset`: this dataset is …
> Adding parser for ot_crispr dataset

- Snakefile
- common/evidence.py
- configuration.yaml
- partner_preview_scripts/ValidationLab.py
- partner_preview_scripts/encore_parser.py
- partner_preview_scripts/ot_crispr.py
Although the snakemake pipeline might not last too long, it makes sense to write up the rules for generating evidence files for PPP. 
- If the snakemake was at some point replaced by other methods, if the rules are available it would easier to make the transition.
- So far there was no documentation on this process. 
**Caveats**:
- The encore datasets are not yet moved to google storage.
- The management of the configuration is not yet fully solved: files are stored in a versioned, private repo, but hard to refer 
and access in a pipeline.
- The standard service account does not yet have write permission on the `gs://OTAR013-PPP/` bucket.  
Issue: [#2911](https://github.com/opentargets/issues/issues/2911)
> Ds 2911 ppp snakemake

- common/evidence.py
- modules/AzGeneBurden.py
- modules/GenebassGeneBurden.py
This PR includes:
- fixes to the problem reported in [#2907](https://github.com/opentargets/issues/issues/2907), where the disease mappings path was hardcoded to the 22.09 release. We now build the path from the project's config YAML
- Spark instance manipulation is no longer handled inside `import_trait_mappings`. It is passed as a parameter instead
This was an important bug to solve because we were not using the most updated version of the disease mappings file.
Luckily, **this error had no impact**. It was only used by the Genebass, and AZ parsers and the curation for their evidence hasn't changed since 22.09.
I've tested it locally with a subset of data and it worked.
> feat: import_trait_mappings reads disease curation from configIl 2907

- configuration.yaml
This PR includes changes to the configuration to run the evidence generation for 24.03:
- EFO updated to 3.62.0
- JSON schema fixed to 2.6.1
- Updated link to baseline expression data. GTEx has changed their folder structure cc @tskir 
- Updated P&D version to 02.2023
> chore: make 23.03 data release

- modules/GeneticsPortal.py
Context: [#3287](https://github.com/opentargets/issues/issues/3287), [#3283](https://github.com/opentargets/issues/issues/3283)
The parser and the data is updated. The data is here:
```
gs://otar000-evidence_input/Genetics_portal/json/genetics-portal-evidence-2024-04-16.json.gz
```
**Questions:**
- Has the number of evidence changed?
- Has the number of evidence with directionality assignment changed?
- How many evidence have different QTL effect?
- How many times did the directionality changed?
**Answers:**
- There's no change in the number of evidence: 811,749
- Verified that the schema of the two datasets is the same.
- The number of evidence with directionality assessment dropped 12% to 210,050, which means 25.8% of evidence have directionality.
- Then number of evidence, where the …
> refactor (genetics parser): changing logic how QTLs processed

- configuration.yaml
- modules/AzGeneBurden.py
This PR closes https://github.com/opentargets/issues/issues/3313
It's pointing to the version of the curation repo that contains the new mappings.
We are also adding significant associations from the synonymous models to be aligned with other sources. These are just 71.
> feat(burden): update AZ config to newer release + include associations from synonymous models

- Snakefile
- configuration.yaml
- modules/Gene2Phenotype.py
This PR includes:
The generated evidence were successfully validated against the current evidence schema.
> refactor(Gene2Phenotype): making code agnosting about the number of panels provided

- Snakefile
- configuration.yaml
- modules/AzGeneBurden.py
- modules/GeneBurden.py
This PR includes:
- Changes to the gene burden evidence:
- New field `releaseVersion`, only present for AZ evidence, containing their release hash. This is extracted from a LUT they have provided with links between genes and their gene pages.
- New field `urls`, only present for AZ evidence, containing a link to their traits page. This is extracted from another provided LUT.
- `studyId` has been dropped. This field only contained GCST IDs for the REGENERON evidence. Even though the GWASCat team helped us in providing trait mappings, this information is empty for 80% of evidence. Together with @buniello and @d0choa, we have agreed to drop this field from the UI
- Updated ChEMBL files
- Pinned EFO version to 3.65.0 and schema version to 2.7.3 (the latest release is 2.7.2 but i have to …
> feat: add links to the AZ evidence + other release things

- Snakefile
- configuration.yaml
- modules/AzGeneBurden.py
- modules/ChEMBL.py
Small changes that fix minor issues to generate data for the 24.06 release.
No red flags, I reckon. I think the CRISPR drop is only because the 24.03 didn’t include your modifications.
- G2P: +492 after the inclusion of the skeletal panel
- Panel App: +1845 with the new version. I think they have improved their disease annotation, because we now have **+2502 evidence with a mapped disease**.
- EVA somatic: -32, slight drop. I'll take a look.
- EVA: +370605. You'll be pleased to know that we have a lot of new variants 😬 (37% increase), probably worth looking with more detail. I'll look at the slight drop in the somatic evidnce.
- ChEMBL: +53791 with data from ChEMBL34. We have evidence for 55 new drugs.
- Burden: +9613 with the update of the AZ Phewas evidence. Here the number of genes is …
> chore: prepare 24.06 release

- configuration.yaml
- partner_preview_scripts/ValidationLab.py
The following updates were implemented:
- The script creates evidence following the schema defined in [this PR](https://github.com/opentargets/json_schema/pull/195)
- The script uses the updated validation lab configuration updated [here](https://github.com/opentargets/PPP-evidence-configuration/blob/master/ValidationLab_config.json)
- The script processes the newly generated data files by the validation lab. (mock data here: `gs://otar013-ppp/validation_lab/input_data/2024.04`)
- The script still relies on the Sanger modell passport data.
Calling the script:
```bash
python partner_preview_scripts/ValidationLab.py \
--output_file output.json.gz \
--parameter_file ../PPP-evidence-configuration/ValidationLab_config.json \
--cell_passport_file …
```
> feat: updating validation lab parser for the new data

- modules/cancerBiomarkers.py
The integration of variant entity in the Platform required to change the name of the a field in the biomarker evidence schema that should be reserved for the variant index.
> fix: change variant field to geneticVariation in cancerBiomarkers parser

- partner_preview_scripts/ValidationLab.py
Assessment field is also changed to plural (assessments) at relevant locations to reflect change to list of strings. These changes are to make the code compatible with downstream considerations.
> fix: update ValidationLab parser to split assessment field by newline

- configuration.yaml
- modules/ChEMBL.py
This PR:
- updates the path to the predicted stopped reasons based on the latest ChEMBL evidence
- adds a mechanism to the ChEMBL parser that raises an error if the file with the predictions is older than the evidence file
I've generated new evidence, and the evidence step in PIS has rerun.
> fix(chembl): update stopReasonCategories file

- Snakefile
- configuration.yaml
- modules/IMPC.py
- partner_preview_scripts/encore_parser.py
- requirements-frozen.txt
- requirements.txt
This PR updates the schema, curation, and EFO versions for the 24.12 release.
scipy (needed for the encore parser) was added to the requirements.
Changes were made to the IMPC, encore, and validation lab parsers.
> Changes made to enable running parsers for 24.12 release

- configuration.yaml
- requirements-frozen.txt
This PR closes https://github.com/opentargets/issues/issues/3485
The new files have brought us 93 new probe/target annotation (an increase of 62 new unique compounds). We should expect information for 27 targets not covered previously, [CES1](https://platform.opentargets.org/target/ENSG00000198848) being an example.
Data available here: `gs://otar001-core/ChemicalProbes/annotation/chemicalProbes-2025-01-10.json.gz`
_Side note:_ I had to delete `pkg_resources==0.0.0` from the lock file because pip was failing with `ERROR: No matching distribution found for pkg_resources==0.0.0`
> feat: update chemical probes to P&D 02.2024 release

- configuration.yaml
- modules/Gene2Phenotype.py
- requirements-frozen.txt
This PR includes:
- Changes to the Gene2Phenotype module and configuration paths to adapt to their new schema of data.
- Update configuration to include latest data, and EFO version (3.77)
- Downgrade of the `h11` due to incompatibility with another library
This branch was the one I used to generate all evidence on the VM, with the exception of Gene2Phenotype which I run locally
> feat: prepare 25.06 release

- configuration.yaml
As of 25th May,  a new GenomicsEngland Panel App data is available. The dataset (coming in excel), got converted to tsv and moved to our buckets. A test run made sure the data is compatible with the old release and the resulting evidence dataset is valid. and shows a moderate increase.
> chore: updating PanelApp input file
