opentargets/evidence_datasource_parsers

.circleci/config.yml
common/EFOData.py
common/GCSUtils.py
common/RareDiseasesUtils.py
modules/Gene2Phenotype.py
modules/GenomicsEnglandPanelApp.py
modules/PheWAS.py
ontology_config.ini
settings.py

refactor code to access Google Cloud Bucket
refactor GenomicsEngland Panel App to map old panel id to new panel id

Gel panel mapping

---

.circleci/config.yml

Cleanup and remove unneeded circle ci commands.

Af circleci cleanup

---

modules/SLAPEnrich.py

JSON evidence strings are only generate if the p-value is < 1e-10 and p-values of 0 are set to 1e-20.

Only generate evidence strings if p-value <1e-4 and deal with p-value==0

---

settings.py

Currently there are some hardcoding to put files in the users home directory. This is really bad practice, and we should stop doing it.

remove evil home-dir hardcoding

---

modules/CRISPR.py
modules/Gene2Phenotype.py
modules/IntOGen.py
modules/PROGENY.py
resources/crispr_descriptions-2019-03-26.tsv
resources/crispr_evidence-2019-03-26.tsv
settings.py

The input data files are in the repository for now. There is a [ticket](https://github.com/opentargets/platform/issues/514) to read and write files from and to Google buckets.

New parser for CRISPR screening data

---

modules/GenomicsEnglandPanelApp.py
modules/IntOGen.py
settings.py

1. Refactoring of Genomics England Panel App plugin (with Miguel, more work to be done on this)
2. Cleaning up unique_association_fields and updating a disease ID and credits & contacts for code (generated a json and evidence strings are identical except for unique_association_fields and additional disease.resource_name field)

MS intogen

---

modules/Gene2Phenotype.py
settings.py

- Updated credit and contact info
- `unique_association_fields`: removed `source_id`, changed `target` to `target_id`

MS - gene2phenotype module update

---

modules/SystemsBiology.py

Updated the 'copyright' section and improved formatting throughout the module.

ms_sysbio - small edits and changes

---

modules/Gene2Phenotype.py

changed .unique_association_fields.disease_uri to .unique_association_fields.disease_id

Small change to unique_association_fields

---

modules/CRISPR.py
resources/crispr_evidence-2019-08-22.tsv
settings.py

* Provide full URL for PMID
* Update settings.py to use updated CRISPR files

MS crispr module updates

---

modules/PROGENY.py

* Fixed export issue (evidence strings can now be exported as JSON file)
* Updated EFO mappings for 3 cancer types
* Code re-formatting and updated comments and TODOs
* Updated unique_association_fields

MS progeny - module updates

---

modules/GeneticsPortal.py
requirements.txt
settings.py

A script to generate evidences based on GWAS associations sourced from the Genetics portal.
* parameters read from command line.
* Duplicated evidences are excluded.
* JSON schema used to build the evidence.
* Logging implemented.

genetics portal evidence

---

modules/GeneticsPortal.py
modules/GeneticsPortal_prepare_data.py

This script pulls together various type of data from OT Genetics portal that will be used to generate GWAS evidences for the platform.
**Input data:**
* Table with top loci
* Table with study related information
* Table with variantindex  
* Table with ECO codes of the variant consequences
The specified tables are read and joined using spark.

Data preparation for genetics portal evidences

---

README.md

The `README.md` file is extended with instructions on how the Genetics Portal evidences are generated.

Update documentation with genetics portal evidence generation.

---

README.md
modules/ClinGen.py

New ClinGen parser and updated README

Ag clingen parser

---

modules/GenomicsEnglandPanelApp.py

Removed duplicates, better documentation and minor tweaks in logic.

[il-panelapp-parser] Genomics England Parser before rewrite

---

README.md
modules/GenomicsEnglandPanelApp.py
settings.py

The parser has undergone very minor fixes, mainly how the export of the output file is done.
The README has been updated with GEL information. The description of the main steps done by the parsers has also been updated.
All references to legacy global variables in the Config class no longer apply, so they've been removed.

[Il panelapp parser] Version for release before rewrite

---

README.md

I merged the SysBio branch without realising that an accent was breaking the markdown 🤫

[README fix]

---

modules/GeneticsPortal.py

* Bugfix: `variantId` was not good: `alt_ref` changed to `ref_alt` 
* In the final json files there were some duplicates.  I removed them.

Genetics portal bugfix

---

modules/cancerBiomarkers.py

Nothing substantial, just cleaning up style fixes.

style fixes to accommodate PEP8

---

common/evidence.py
partner_preview_scripts/ValidationLab.py
partner_preview_scripts/ValidationLab_parameters.json
partner_preview_scripts/encore_parameters.json
partner_preview_scripts/encore_parser.py
partner_preview_scripts/ot_crispr.py

This branch remains a draft PR until the partner preview is released. Due to the frequent updates this branch is not needed to be reviewed until the release of the partner preview. Make sure no sensitive data is committed to the branch!
**Parsers:**
**Further tasks**:

Branch collecting code for parsing data for the partner preview.

---

configuration.yaml

Some changes that are needed after #2805

update curation and schema versions

---

configuration.yaml
modules/GenebassGeneBurden.py
requirements-frozen.txt

This PR includes the changes proposed in #2808 plus some needed version updates in the configuration yaml.

Genebass effect sizes reported as betas

---

modules/GeneticsPortal.py

Adding new column to genetics evidence based on colocalization with QTL.
Addressing task: [#2840](https://github.com/opentargets/issues/issues/2840)

feat: adding QTL effect size to genetics

---

modules/GenebassGeneBurden.py
modules/TargetSafety.py

The column name was changed and still was being referenced in other places of the parser. Sorry for the branch name, it has nothing to do with the Nightingale curation.

Minor bug in the Genebass parser

---

configuration.yaml
modules/ChEMBL.py

Accommodate "Uncategorised" ChEMBL label

---

configuration.yaml
modules/IntOGen.py
resources/cancer2EFO_mappings.tsv

Updating parser for 2023.05 Intogen release.

---

modules/GeneBurden.py

OK, I was sloppy with the review. :D

fix: some bits were still missing

---

modules/TargetSafety.py

Based on https://github.com/opentargets/issues/issues/2851

chore(safety): remove human applicability flag

---

configuration.yaml

Trivial update pointing to the newly released panelapp data.

chore(configuration): adding new panelapp file to configuration

---

modules/GeneBurden.py

Necessary changes for a successful run of the Burden parser for 24.09.

fix(burden): minor bugs for data validation

---

modules/TargetSafety.py

This PR reverts this commit 477324449ddd9b8b7dae0aaf772af018d1862432 that is causing an issue in the ETL.
In the safety dataset, there are two scenarios:
1. The target is mapped to an ID in Ensembl: In this case, the ID will be in the `id` column.
2. The target is not mapped to an ID: In this case, the symbol will be in the `targetFromSourceId` column.
I unified the code so that both IDs appeared in the id column. I thought the id mapping step for the safety dataset in the ETL was the same as the one for evidence: it takes one column as an input, where there could be IDs or symbols, and it returns one column of Ensembl IDs. It's not the case, the logic in the ETL expects a `targetFromSourceId` column with just symbols.
Pending the unification of this logic in the ETL, I'll revert the …

revert(safety): revert 477324449ddd9b8b7dae0aaf772af018d1862432

---

Snakefile

The PPP rules are now being integrated into the main pipeline of the evidence generation.

fix(ppp): integrating PPP rules into snakemake pipeline

---

configuration.yaml

Just changing configuration pointing to the updated PanelApp dataset.

feat: updating panelapp data

---

Snakefile
configuration.yaml

Integrate new disease panel on Gene2Phenotype.

chore: update Gene2Phenotype sources

---

configuration.yaml
modules/GeneBurden.py

Closes https://github.com/opentargets/issues/issues/3621

feat(gene_burden): update finngen burden results to R12

---

configuration.yaml
modules/GeneBurden.py
modules/Orphanet.py

chore: 25.03 release specific updates

---

configuration.yaml

This closes https://github.com/opentargets/issues/issues/3785
Generated data available at `gs://otar000-evidence_input/Gene2Phenotype/json/gene2phenotype-2025-02-26.json.gz`

chore(g2p): fetch data from FTP

---

configuration.yaml

Closes https://github.com/opentargets/issues/issues/3801

chore: update probes&drugs data to 01.2025 version
